### ISSUE TITLE
Wrong property name in application.properties

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/connector-template-outbound#79]
__Describe the Bug__

zeebe.broker.gateway-address should be zeebe.client.broker.gateway-address in the application.properties

__Steps to Reproduce__

1. sert a value for zeebe.broker.gateway-address
2. won't work, still tries to connect to 0.0.0.0:26500

__Expected Behavior__

If you change this property it should try to connect on that path.

__Environment__

- OS: Windows 10
- Library version: latest

**Comment by sbuettner** [comment]
@markfarkas-camunda This can be closed as well right?

**Comment by markfarkas-camunda** [comment]
Done with this PR: https://github.com/camunda/connector-template-outbound/pull/83
